### ISSUE TITLE
ComputeCpp_INCLUDE_DIRS

### ISSUE THREAD

**Issue by jinz2014** [codeplaysoftware/sycl-blas#180]
I think users need to set ComputeCpp_INCLUDE_DIRS in addition to ComputeCpp_DIR before building the software using ninja.

**Comment by rodburns** [comment]
Can you provide some steps to reproduce the problem you have experienced? Then we can investigate if things need to change or a fix needs to be made. Thanks.

**Comment by DuncanMcBain** [comment]
To clarify: the value of `ComputeCpp_INCLUDE_DIRS` is set by the CMake configuration, derived from `ComputeCpp_DIR`. If this isn't working, it is possibly a bug (or possibly a problem with your local setup).

**Comment by jinz2014** [comment]
Sorry, I couldn't reproduce the issue again on another node. I will close the issue. 

Thanks again.
