### ISSUE TITLE
run test and benchmark test

### ISSUE THREAD

**Issue by jinz2014** [codeplaysoftware/sycl-blas#181]
Can you please specify the commands to run your tests and benchmark ?

Thanks

**Comment by Nyrio** [comment]
Hi,

The benchmarks have a comprehensive documentation in [benchmark/README.md](https://github.com/codeplaysoftware/sycl-blas/tree/master/benchmark).

The tests are run with CTest (it's mentioned in the main `README.md` but I reckon it could be explained better). After compiling the project with the tests, in your build folder you can simply run `ctest` to run all the tests, or if you want to run a specific test on a specific device you can invoke the executable, e.g `./test/unittest/blas3_gemm_test --device=intel:gpu`

I will update the documentation with more information about the tests and benchmarks.
