### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by jinz2014** [codeplaysoftware/sycl-blas#182]
Can you please provide some examples (matrix multiply, matrix vector multiply, etc) that use SYCL-BLAS ?   

Thanks

**Comment by Nyrio** [comment]
It would be useful, you are right. We will add some examples.

**Comment by jinz2014** [comment]
Then, people will know how to migrate a program using CBLAS or Intel BLAS to a program  using SYCL BLAS.

Thanks.

**Comment by jinz2014** [comment]
It is true that the test cases are kind of examples. It is not clear if we should imitate these test cases when migrating a program using CBLAS or Intel BLAS to a program using SYCL BLAS. It is helpful to know a couple of ways to write a SYCL program using SYCL-BLAS for the purposes of test and performance.

Thanks
