### ISSUE TITLE
Small matrix support

### ISSUE THREAD

**Issue by r-potter** [codeplaysoftware/sycl-blas#87]
In SYCL-DNN we have various handwritten tests that operate on small matrices to verify that the underlying matmul implementation is being used correctly.

These tests currently fail on SYCL-BLAS. Further investigation has revealed that SYCL-BLAS performs incorrectly for matrices under 15x15. For example, a 3x3 matrix multiply only computes the first row, leaving the last two rows in their initial state.

**Comment by mehdi-goli** [comment]
Fixed
